# Generated by Django 6.0 on 2026-01-05 03:46

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_extractedlineitem_ledger_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='business',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', 'Invalid GSTIN format')]),
        ),
        migrations.AlterField(
            model_name='business',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]$', 'Invalid PAN format')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=core.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tiff'])]),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['created_by'], name='core_busine_created_260be4_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['name'], name='core_busine_name_b3e876_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['business'], name='core_docume_busines_4c79f9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='core_docume_uploade_8c924b_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedlineitem',
            index=models.Index(fields=['document'], name='core_extrac_documen_4b8a28_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedlineitem',
            index=models.Index(fields=['vendor'], name='core_extrac_vendor_94b9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedlineitem',
            index=models.Index(fields=['invoice_no'], name='core_extrac_invoice_1b6fb1_idx'),
        ),
    ]
