# Generated by Django 6.0 on 2026-01-05 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_business_options_alter_document_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='business',
            name='core_busine_name_b3e876_idx',
        ),
        migrations.AddField(
            model_name='business',
            name='financial_year_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='last_draft_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Actual business owner / client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='onboarding', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='checksum',
            field=models.CharField(blank=True, help_text='Used to detect duplicate uploads', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, help_text='Invoice / reference number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractedlineitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extractedlineitem',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner'], name='core_busine_owner_i_3dfbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status'], name='core_busine_status_ebf13f_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['financial_year_start'], name='core_busine_financi_9939f3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type'], name='core_docume_doc_typ_a55021_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_number'], name='core_docume_documen_19a7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedlineitem',
            index=models.Index(fields=['ledger_account'], name='core_extrac_ledger__7d4874_idx'),
        ),
    ]
